lib/chat_web/router.ex
defmodule ChatWeb.Router do
  use ChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChatWeb.Plugs.FetchUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatWeb do
    pipe_through :browser

    get "/", PageController, :index

    get("/sign-in", SessionController, :new)
    post("/sign-in", SessionController, :create)
    delete("/sign-out", SessionController, :delete)

    get("/register", RegistrationController, :new)
    post("/register", RegistrationController, :create)
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatWeb do
  #   pipe_through :api
  # end
end

lib/chat/application.ex
defmodule Chat.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Chat.Repo,
      # Start the endpoint when the application starts
      ChatWeb.Endpoint
      # Starts a worker by calling: Chat.Worker.start_link(arg)
      # {Chat.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Chat.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ChatWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/chat/message.ex
defmodule Chat.Message do
  use Ecto.Schema
  import Ecto.Changeset

  schema "messages" do
    field :message, :string
    field :name, :string

    timestamps()
  end

  def get_messages(limit \\ 20) do
    Chat.Repo.all(Chat.Message, limit: limit)
  end

  @doc false
  def changeset(message, attrs) do
    message
    |> cast(attrs, [:name, :message])
    |> validate_required([:name, :message])
  end
end

lib/chat/repo.ex
defmodule Chat.Repo do
  use Ecto.Repo,
    otp_app: :chat,
    adapter: Ecto.Adapters.Postgres
end

lib/chat/users.ex
defmodule Chat.Users do
  alias Chat.Users.User

  alias Chat.Repo

  alias Stein.Accounts

  def new(), do: Ecto.Changeset.change(%User{}, %{})

  def create(params) do
    changeset = User.create_changeset(%User{}, params)

    case Repo.insert(changeset) do
      {:ok, user} ->
        user
        #        |> Emails.welcome_email()
        #        |> Mailer.deliver_later()

        {:ok, user}

      {:error, changeset} ->
        {:error, changeset}
    end
  end

  def from_token(token) do
    case Repo.get_by(User, token: token) do
      nil ->
        {:error, :not_found}

      user ->
        {:ok, user}
    end
  end

  def update(user, params) do
    changeset = User.update_changeset(user, params)

    case Repo.update(changeset) do
      {:ok, user} ->
        {:ok, user}

      {:error, changeset} ->
        {:error, changeset}
    end
  end

  def validate_login(email, password) do
    Accounts.validate_login(Repo, User, email, password)
  end
end

lib/chat/users/user.ex
defmodule Chat.Users.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :email, :string
    field :first_name, :string
    field :last_name, :string
    field :password, :string
    field :password_confirmation, :string, virtual: true
    field :password_hash, :string
    field :token, :string

    field(:email_verification_token, Ecto.UUID)
    field(:email_verified_at, :utc_datetime)

    field(:password_reset_token, Ecto.UUID)
    field(:password_reset_expires_at, :utc_datetime)
    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:token, :email, :first_name, :last_name, :password, :password_hash])
    |> validate_required([:token, :email, :first_name, :last_name, :password, :password_hash])
  end

  def create_changeset(struct, params) do
    struct
    |> cast(params, [:email, :first_name, :last_name, :password, :password_confirmation])
    |> put_change(:token, UUID.uuid4())
    |> validate_confirmation(:password)
    |> Stein.Accounts.hash_password()
    |> Stein.Accounts.start_email_verification_changeset()
    |> validate_required([:email, :first_name, :last_name, :password_hash])
    |> unique_constraint(:email, name: :users_lower_email_index)
  end

  def update_changeset(struct, params) do
    struct
    |> cast(params, [:email, :first_name, :last_name])
    |> validate_required([:email, :first_name, :last_name])
    |> unique_constraint(:email, name: :users_lower_email_index)
  end
end

lib/chat_web/controllers/page_controller.ex
defmodule ChatWeb.PageController do
  use ChatWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/chat_web/controllers/registration_controller.ex
defmodule ChatWeb.RegistrationController do
  use ChatWeb, :controller

  alias Chat.Users

  action_fallback(Web.FallbackController)

  plug(:put_layout, "session.html")

  def new(conn, _params) do
    conn
    |> assign(:changeset, Users.new())
    |> render("new.html")
  end

  def create(conn, %{"user" => params}) do
    case Users.create(params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome to Chat")
        |> put_session(:user_token, user.token)
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, changeset} ->
        conn
        |> put_flash(:error, "There was an error, please try again")
        |> put_status(422)
        |> assign(:changeset, changeset)
        |> render("new.html")
    end
  end
end

lib/chat_web/controllers/session_controller.ex
defmodule ChatWeb.SessionController do
  use ChatWeb, :controller

  alias Chat.Users

  def new(conn, _params) do
    conn
    |> put_layout("session.html")
    |> assign(:changeset, Users.new())
    |> render("new.html")
  end

  def create(conn, %{"user" => %{"email" => email, "password" => password}}) do
    case Users.validate_login(email, password) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "You have signed in.")
        |> put_session(:user_token, user.token)
        |> after_sign_in_redirect(Routes.page_path(conn, :index))

      {:error, :invalid} ->
        conn
        |> put_flash(:error, "Your email or password is invalid")
        |> redirect(to: Routes.session_path(conn, :new))
    end
  end

  def delete(conn, _params) do
    conn
    |> clear_session()
    |> redirect(to: Routes.page_path(conn, :index))
  end

  @doc """
  Redirect to the last seen page after being asked to sign in
  Or the home page
  """
  def after_sign_in_redirect(conn, default_path) do
    case get_session(conn, :last_path) do
      nil ->
        redirect(conn, to: default_path)

      path ->
        conn
        |> put_session(:last_path, nil)
        |> redirect(to: path)
    end
  end
end

lib/chat_web/views/error_view.ex
defmodule ChatWeb.ErrorView do
  use ChatWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/chat_web/views/layout_view.ex
defmodule ChatWeb.LayoutView do
  use ChatWeb, :view
end

lib/chat_web/views/page_view.ex
defmodule ChatWeb.PageView do
  use ChatWeb, :view
end

lib/chat_web/views/registration_view.ex
defmodule ChatWeb.RegistrationView do
  use ChatWeb, :view

  alias Stein.Phoenix.Views.FormView
end

lib/chat_web/views/session_view.ex
defmodule ChatWeb.SessionView do
  use ChatWeb, :view
end

lib/chat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Chat · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md" role="menubar">
        <div class="container">
          <%= link(to: Routes.page_path(@conn, :index), class: "navbar-brand") do %>
            Chat
          <% end %>

          <div class="collapse navbar-collapse" id="navbarLinks">
            <ul class="navbar-nav ml-auto">
              <%= if Map.has_key?(assigns, :current_user) do %>
                <li class="nav-item">
                  <%= link("Sign Out", to: Routes.session_path(@conn, :delete), method: :delete, class: "nav-link") %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link("Register", to: Routes.registration_path(@conn, :new), class: "nav-link") %>
                </li>
                <li class="nav-item">
                  <%= link("Sign In", to: Routes.session_path(@conn, :new), class: "nav-link") %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/chat_web/templates/layout/session.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content="<%= Plug.CSRFProtection.get_csrf_token() %>">
    <title>Chat Example</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body class="bg-gradient-primary">
    <div class="container">
      <%= if get_flash(@conn, :info) do %>
        <div class="card bg-primary text-white shadow mt-5">
          <div class="card-body">
            <%= get_flash(@conn, :info) %>
          </div>
        </div>
      <% end %>

      <%= if get_flash(@conn, :error) do %>
        <div class="card bg-danger text-white shadow mt-5">
          <div class="card-body">
            <%= get_flash(@conn, :error) %>
          </div>
        </div>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </div>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/chat_web/templates/page/index.html.eex
<div class="jumbotron">
  <h1 class="display-4"><%= gettext "Welcome to %{name}!", name: "Chat" %></h1>
</div>


<%= if Map.has_key?(assigns, :current_user) do %>
  <!-- The list of messages will appear here: -->
  <ul id='msg-list' class='row' style='display:block;list-style: none; min-height:200px; padding: 10px;'></ul>

  <div class="row">
    <div class="col-xs-3">
      <input type="text" id="name" class="form-control" disabled value="<%= assigns[:current_user].first_name %>" autofocus>
    </div>
    <div class="col-xs-9">
      <input type="text" id="msg" class="form-control" placeholder="Your Message">
    </div>
  </div>

<% end %>

lib/chat_web/templates/session/new.html.eex
<div class="row justify-content-center">
  <div class="col-xl-10 col-lg-12 col-md-9">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <div class="row h-100">
          <div class="col-lg-6 my-auto">
            <h1 class="text-center my-auto">Chat</h1>
          </div>
          <div class="col-lg-6">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
              </div>
              <%= form_for(@changeset, Routes.session_path(@conn, :create), fn f -> %>
                <div class="form-group">
                  <%= text_input(f, :email, type: :email, class: "form-control", placeholder: "Email") %>
                </div>
                <div class="form-group">
                  <%= password_input(f, :password, class: "form-control", placeholder: "Password") %>
                </div>
                <%= submit("Login", class: "btn btn-primary") %>
                <%= link("Register", to: Routes.registration_path(@conn, :new), class: "btn btn-default") %>
              <% end) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>